export default {
  GET_REPOS_REQUEST: 'GET_REPOS_REQUEST',
  GET_REPOS_REQUEST_SUCCESS: 'GET_REPOS_REQUEST_SUCCESS',
  GET_REPOS_REQUEST_ERROR: 'GET_REPOS_REQUEST_ERROR',
  GET_AUTH_REPOS_REQUEST: 'GET_AUTH_REPOS_REQUEST',
  GET_AUTH_REPOS_REQUEST_SUCCESS: 'GET_AUTH_REPOS_REQUEST_SUCCESS',
  GET_AUTH_REPOS_REQUEST_ERROR: 'GET_AUTH_REPOS_REQUEST_ERROR',
};