export default {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  REPOS_REQUEST: 'REPOS_REQUEST',
  REPOS_REQUEST_SUCCESS: 'REPOS_REQUEST_SUCCESS',
  REPOS_REQUEST_ERROR: 'REPOS_REQUEST_ERROR',
};