export default {
  CURRENT_USER: 'CURRENT_USER',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SET_USER_TOKEN: 'SET_USER_TOKEN',
  CLEAR_USER_TOKEN: 'CLEAR_USER_TOKEN',
  REPOS_REQUEST: 'REPOS_REQUEST',
  REPOS_REQUEST_SUCCESS: 'REPOS_REQUEST_SUCCESS',
  REPOS_REQUEST_ERROR: 'REPOS_REQUEST_ERROR',
};